id: 13ff41115e674329a78ffd7efcb9fe37
name: Active Directory Parsing DLL Loaded Via Office Applications
path: /Advanced Threat Detection/Windows Process Monitoring
description: Detects DSParse DLL being loaded by an Office Product
type: standard
author: community
entity_type: workbooks
blocks:
- type: text
  code: "|Author|References|\n                 |------|--------|\n               \
    \  |Antonlovesdnb|https://medium.com/threatpunter/detecting-adversary-tradecraft-with-image-load-event-logging-and-eql-8de93338c16|"
- type: sql
  query: SELECT * FROM SYSMON-IMAGE-LOAD WHERE (($Image LIKE "%\\winword.exe" OR $Image
    LIKE "%\\powerpnt.exe" OR $Image LIKE "%\\excel.exe" OR $Image LIKE "%\\outlook.exe")
    AND ($ImageLoaded LIKE "%\\dsparse.dll%"))
- type: signal
  DetectionName: Active Directory Parsing DLL Loaded Via Office Applications
  DetectionTactic: Execution
  DetectionTechnique: User Execution
  DetectionScore: 5
  DetectionConfidence: Low
  TargetHost: $System
config: {}
